FFA/FFA/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Freeforall.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

FFA/Freeforall/urls.py
from django.urls import path
from . import views

app_name = "Freeforall"

urlpatterns = [

    path('', views.index, name="index" ),
    path('login/', views.login, name="login" ),
    path('login/nuevo', views.loginFormulario, name="loginFormulario" ),
    path('logout/', views.logout, name="logout" ),
    path('login/register', views.formularioRegister, name="nuevoRegistro" ),
    path('login/nuevo', views.formularioRegister, name="nuevoRegistro" ),

    path('restablecer/',views.restablecer, name="restablecer"),
    path('showRestablecer/',views.showRestablecer, name="showRestablecer"),
    path('restablecerPassword/<id>', views.cambiarPassword, name="restablecerPassword"),
    path('cambiarPws/', views.cambiarPws, name="cambiarPws"),

    path('invitacion/enviar/<id>',views.formInvitacion, name="nuevoInvitacion"),
    path('invitacion/',views.invitacion, name="invitacion"),


    path('usuarios', views.listarUsuarios, name='listarUsuarios'),
    path('usuarios/nuevo', views.formularioUsuario, name='nuevoUsuario'),
    path('usarios/guardar', views.guardarUsuario, name='guardarUsuario'),
    path('usarios/actualizar/<id>', views.editarUsuario, name='editarUsuario'),
    path('usarios/editar', views.actualizarUsuario, name='actualizarUsuario'),

    path('ligas', views.listarLigas, name='listarLigas'),
    path('ligas/nuevo', views.formularioLiga, name='nuevoliga'),
    path('ligas/guardar', views.guardarLiga, name='guardarLiga'),
    path('ligas/eliminar/<id>', views.eliminarLiga, name='eliminarLiga'),
    path('ligas/actualizar/<id>', views.editarLiga, name='editarLiga'),
    path('ligas/editar', views.actualizarLiga, name='actualizarliga'),

    path('eventos', views.listarEventos, name='listarEventos'),
    path('eventos/nuevo', views.formularioEvento, name='nuevoEvento'),
    path('eventos/guardar', views.guardarEvento, name='guardarEvento'),
    path('eventos/eliminar/<id>', views.eliminarEvento, name='eliminarEvento'),
    path('eventos/actualizar/<id>', views.editarEvento, name='editarEvento'),
    path('eventos/editar', views.actualizarEvento, name='actualizarEvento'),
    path('eventos/competidor/<pk>', views.ADDcompetidor, name='competidor'),
    path('eventos/espectador/<pk>', views.ADDespectador, name='espectador'),

    path('comentarios', views.listarComentarios, name='listarComentarios'),
    path('comentarios/nuevo/<id>', views.formularioComentarios, name='nuevoComentarios'),
    path('comentarios/guardar', views.guardarComentarios, name='guardarComentarios'),
    path('comentarios/eliminar/<id>', views.eliminarComentarios, name='eliminarComentarios'),
    path('comentarios/actualizar/<id>', views.editarComentarios, name='editarComentarios'),
    path('comentarios/editar', views.actualizarComentarios, name='actualizarComentarios'),

    path('perfil/<id>', views.perfil, name='perfil'),

]

FFA/Freeforall/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Login(models.Model):
    id_usuario = models.CharField(max_length=50, blank=False, null=False)


    def __str__(self):
        return f"{self.id_usuario} - {self.id_usuario}"

class Usuarios(models.Model):
    """Esta modelo recibe los datos de los usuarios"""
    id_usuario = models.AutoField(primary_key=True)
    primer_nombre = models.CharField(max_length=20, blank=False, null=False)
    segundo_nombre = models.CharField(max_length=20, blank=False, null=False)
    primer_apellido =models.CharField(max_length=20, blank=False, null=False)
    segundo_apellido = models.CharField(max_length=30, blank=False, null=False)
    email = models.EmailField( blank=False, null=False, unique=True)
    fecha_de_nacimiento = models.DateTimeField()
    clave = models.CharField(max_length=254)
    ROLES = (
        ('A', 'Administrador'),
        ('E', 'Espectador'),
        ('C', 'Creador'),
    )
    rol = models.CharField(max_length=100, choices=ROLES, default='O')
    ESTADOS = (
        ('A', 'Activado'),
        ('D', 'Desactivado'),
        
    )
    estado = models.CharField(max_length=100,  choices=ESTADOS, default='Activado')
    
    
    

    def __str__(self):
        return f"{self.primer_nombre}"

class Invitaciones(models.Model):
    """Esta modelo recibe los datos de las invitaciones"""
    id_invitaciones = models.AutoField(primary_key=True) 
    nombre_invitacion = models.CharField(max_length=20, blank=False, null=False)
    email = models.EmailField( blank=False, null=False, unique=True)
    
    def __str__(self):
        return f"{self.id_invitaciones}"

class Liga(models.Model):
    """Esta modelo recibe los datos de las ligas"""
    id_liga = models.AutoField(primary_key=True) 
    nombre_liga = models.CharField(max_length=20, blank=False, null=False, unique=True)

    
    def __str__(self):
        return f"{self.nombre_liga}"

class Evento(models.Model):
    """Esta modelo recibe los datos de los Eventos"""
    id_evento = models.AutoField(primary_key=True)
    nombre_evento = models.CharField(max_length=15, blank=False, null=False, unique=True)
    fecha_inicio =  models.DateTimeField()
    feha_fin =  models.DateTimeField()
    ubicacion = models.CharField(max_length=15, blank=False, null=False)
    precio = models.IntegerField(null=False, blank=False)
    Municipio= models.CharField(max_length=15, blank=False, null=False)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, null=True, blank=True)
    id_liga = models.ForeignKey(Liga, on_delete=models.DO_NOTHING, null=True, blank=True)
    foto = models.ImageField(upload_to = 'Freeforall/fotos', default='Freeforall/fotos/default.webp')
    ESTADOS = (
        ('A', 'Activado'),
        ('D', 'Desactivado'),
        
    )
    estado = models.CharField(max_length=100,  choices=ESTADOS, default='Activado')
    def __str__(self):
        return f"{self.id_evento}"



class Comentarios(models.Model):
    """Esta modelo recibe los datos de los comentarios"""
    id_comentarios =  models.AutoField(primary_key=True)
    comentarios = models.CharField(max_length=15, blank=False, null=False)
    id_evento = models.ForeignKey(Evento, on_delete=models.CASCADE, null=True, blank=True)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return f"{self.id_comentarios} - {self.comentarios}"

FFA/Freeforall/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib import messages
# Create your views here.
from django.core.paginator import Paginator
from django.core.files.storage import FileSystemStorage

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

from os import remove, path
def index(request):
    return render(request, 'Freeforall/index.html')

"""Login"""
def loginFormulario(request):
    """Redirecciona al formulario del login

    Returns:
        template:`Freeforall/login/login.html`
    
    """
    return render(request, 'Freeforall/login/login.html')

def login(request):
    """Se usa para validar el email y la clave y dar los permisos dependiendo el rol (A),(E),(C)

    Arg:
    login: Optiene los datos para la sesion

    Returns:
        template:`Freeforall:listarEventos`
    
    """
    if request.method == "POST":
        try:
            mail = request.POST["email"]
            passw = request.POST["clave"]

            usuarios = Usuarios.objects.get(email = mail, clave = passw)
            # crear la sesión
            request.session["logueo"] = [usuarios.primer_nombre,usuarios.primer_apellido, usuarios.rol, usuarios.id_usuario, usuarios.get_rol_display()]
            # ----------------------------
            messages.success(request, "Bienvenido!!")
            return redirect('Freeforall:listarEventos')     

        except Usuarios.DoesNotExist:
            messages.error(request, "Usuario no Existe")
            return redirect('Freeforall:loginFormulario')
        except Exception as e:
            messages.error(request, f"Error: {e}")
            return redirect('Freeforall:loginFormulario')
    else:
        return redirect('Freeforall:loginFormulario')

def logout(request):
    """Se usa para validar el email y la clave y dar los permisos dependiendo el rol (A),(E)


        Returns:
            template:`Freeforall:loginFormulario`
    """

    try:
        del request.session["logueo"]
        messages.success(request, "Sesión cerrada correctamente!!")
        return redirect('Freeforall:index')
    except Exception as e:
        messages.error(request, f"Error: {e}")
        return redirect('Freeforall:index')

def formularioRegister(request):
    """Redirecciona al formulario del Register

    Returns:
        template:`Freeforall/login/register.html`
    
    """
    return render(request, 'Freeforall/login/register.html')        
 
"""Usuarios"""

def listarUsuarios(request):
    """Se usa para listar los usuarios existentes

    Returns:
        template:`Freeforall/usuarios/usuarios.html`
    
    """
    usuarios = Usuarios.objects.all()
    return render(request, 'Freeforall/usuarios/usuarios.html', {"usuarios":  usuarios})   

def formularioUsuario(request):
    """Redirecciona al formulario del Usuario

    Returns:
        template:`Freeforall/usuarios/nuevo.html`
    
    """
    return render(request, 'Freeforall/login/register.html')

def guardarUsuario(request):
    """Se usa para guardar un usuario

    Arg:
    Usuario: Optiene los datos para registrar los usuarios,('id_usuario', 'estado', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'email', 'fecha_de_nacimiento', 'clave', 'ROLES', 'rol', )

    Returns:
        template:`Freeforall:listarEventos`
    """

    try:
        usuario = Usuarios( 
            primer_nombre = request.POST["primer_nombre"],
            segundo_nombre = request.POST["segundo_nombre"],
            primer_apellido = request.POST["primer_apellido"],
            segundo_apellido = request.POST["segundo_apellido"],
            email = request.POST["email"],
            fecha_de_nacimiento = request.POST["fecha_de_nacimiento"],
            clave = request.POST["clave"],
            rol = request.POST["rol"],
        )
        usuario.save()
        messages.success(request, "Usuario guardado correctamente!!")
    except:
        messages.error(request, "Usuario no tiene los datos nesesarios")
        return render(request, 'Freeforall/login/register.html')

    return redirect('Freeforall:listarEventos')

def editarUsuario(request, id):
    """Redirecciona al formulario editar Usuario

    Returns:
        template:`Freeforall/usuarios/actualizar.html`
    """

    usuarios = Usuarios.objects.get(id_usuario = id)
    return render(request, 'Freeforall/usuarios/actualizar.html', {"usuarios": usuarios})

def actualizarUsuario(request):
    """Se usa para actualizar un usuario

    Arg:
    Usuario: Optiene los datos para actualizar los usuarios,('id_usuario', 'estado', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'email', 'fecha_de_nacimiento', 'clave', 'ROLES', 'rol', )

    Returns:
        template:`Freeforall/usuarios/actualizar.html`
    """
    try:
        usuarios = Usuarios.objects.get(id_usuario = request.POST["id_usuario"])
        usuarios.primer_nombre = request.POST["primer_nombre"]
        usuarios.segundo_nombre = request.POST["segundo_nombre"]
        usuarios.primer_apellido = request.POST["primer_apellido"]
        usuarios.segundo_apellido = request.POST["segundo_apellido"]
        usuarios.email = request.POST["email"]
        usuarios.fecha_de_nacimiento = request.POST["fecha_de_nacimiento"]
        usuarios.clave = request.POST["clave"]
        usuarios.rol = request.POST["rol"]
        usuarios.save()
        messages.success(request, "Usuario actualizado correctamente")
    except:
        messages.error(request, "Usuario actualizado correctamente")
        return redirect('Freeforall:editarUsuario')


    return redirect('Freeforall:listarUsuarios')

"""Ligas"""


def listarLigas(request):
    """Se usa para listar las ligas existentes

    Returns:
        template:`Freeforall/ligas/ligas.html`
    
    """
    ligas = Liga.objects.all()
    return render(request, 'Freeforall/ligas/ligas.html', {"ligas":  ligas})   

def formularioLiga(request):
    """Redirecciona al formulario de liga

    Returns:
        template:`Freeforall/ligas/nuevo.html`
    
    """
    return render(request, 'Freeforall/ligas/nuevo.html')

def guardarLiga(request):
    """Se usa para guardar una liga

    Arg:
    Usuario: Optiene los datos para registrar las ligas,('id_liga', 'nombre_liga', )

    Returns:
        template:`Freeforall:listarLigas`
    """
    try:
        if request.method == "POST":
            liga = Liga( 
                nombre_liga = request.POST["nombre_liga"],
            )
            liga.save()
            messages.success(request, "Producto guardado correctamente!!")
        else:
            messages.warning(request, "Usted no ha enviado datos...")
    except Exception as e:
        messages.error(request, f"Error: {e}")
        return render(request, 'Freeforall/ligas/nuevo.html')

    return redirect('Freeforall:listarLigas')

def formularioEditarLiga(request):
    """Redirecciona al formulario del Usuario

    Returns:
        template:`Freeforall/ligas/actualizar.html'`
    
    """
    return render(request, 'Freeforall/ligas/actualizar.html')    

def eliminarLiga(request, id):
    """Se usa para eliminar una liga

    Arg:
    Usuario: Optiene el id  eliminar una liga

    Returns:
        template:`Freeforall:listarLigas`
    """
    try:
        liga = Liga.objects.get(id_liga = id)
        liga.delete()
        pass
    except Exception as e:
        messages.error(request, f"Error: {e}")
    return redirect('Freeforall:listarLigas')

def editarLiga(request, id):
    """Redirecciona al formulario editar Liga

    Returns:
        template:`Freeforall/ligas/actualizar.html`
    """
    liga = Liga.objects.get(id_liga = id)
    return render(request, 'Freeforall/ligas/actualizar.html', {"liga": liga})

def actualizarLiga(request):

    """Se usa para actualizar un usuario

    Arg:
    Usuario: Optiene los datos para actualizar los usuarios,('id_liga', 'nombre_liga', )

    Returns:
        template:`Freeforall/usuarios/actualizar.html`
    """
    try:
        liga = Liga.objects.get(id_liga = request.POST["id_liga"])
        liga.nombre_liga = request.POST["nombre_liga"],
        liga.save()
        messages.success(request, "Liga Actualizada correctamente!!")
    except Exception as e:
        messages.error(request, f"Error: {e}")
        messages.error(request, "Liga no se puedo actualizar!!")

    return redirect('Freeforall:listarLigas') 

#Eventos   


def listarEventos(request):
    """Se usa para listar los eventos existentes

    Returns:
        template:`Freeforall/eventos/eventos.html`
    
    """
    comentarios = Comentarios.objects.all()
    eventos = Evento.objects.all().order_by('-id_evento')
    return render(request, 'Freeforall/eventos/eventos.html',{"eventos":  eventos, "comentarios":  comentarios})
    
def formularioEvento(request):
    """Redirecciona al formulario de evento

    Returns:
        template:`Freeforall/evento/nuevo.html`
    
    """
    ligas = Liga.objects.all()
    usuarios = Usuarios.objects.all()
    return render(request, 'Freeforall/eventos/nuevo.html', {"ligas":  ligas, "usuarios":  usuarios})

def guardarEvento(request):
    """Se usa para guardar un evento

    Arg:
    Usuario: Optiene los datos para registrar los eventos,('id_liga', 'nombre_liga', )
    ('id_evento', 'nombre_evento', 'fecha_inicio', 'feha_fin', 'ubicacion', 'precio', 'Municipio', 'id_usuario', 'id_liga', 'foto', )

    Returns:
        template:`Freeforall:listarEventos`
    """
    try:
        if request.method == "POST":
            if request.FILES:

FFA/Freeforall/templates/Freeforall/comentarios/actualizar.html
{% extends 'Freeforall/base.html' %}
{% load static %}

{% block contenedor %}
{% if request.session.logueo.2 == 'A' or request.session.logueo.2 == 'E' or request.session.logueo.2 == 'C'  %}
<br>
<br><br>
<br>
<br><br>
<div class="container">
    <div class="row">
       <div class="col-md-12 ">
          <div class="titlepage">
             <h2>Editar comentario</h2>
             <span> llena cada campo con los datos indicados</span>
          </div>
       </div>
    </div>
<div class="container">
    <div class="row">
        <form class="col s12" action="{% url 'Freeforall:actualizarComentarios' %}" method="POST">{% csrf_token %}
            <div class="row">
                <input value="{{comentarios.id_comentarios}}" type="hidden" name="id_comentarios">
                <label for="titulo">Comentario</label>
                    <div class="input-field col s12">
                        <input value="{{comentarios.comentarios}}" id="titulo" type="text" class="form-control" name="comentarios" required>
                    </div>
                    <label for="titulo">Usuario</label>
                    <div class="input-field col s12">
                        <input value="{{ request.session.logueo.3 }}" id="titulo" type="hidden" class="form-control" name="usuarios" required>
                    </div>
                    <label for="titulo">Evento</label>
                    <div class="input-field col s12">
                        <input value="{{ comentarios.id_evento }}" id="titulo" type="hidden" class="form-control" name="eventos" required>
                    </div>
                <div class="form-btns">
                    <button type="submit" class="btn btn-primary">Guardar liga</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

FFA/Freeforall/templates/Freeforall/comentarios/comentarios.html
{% extends 'Freeforall/base.html' %}
{% load static %}

{% block contenedor %}
{% if request.session.logueo.2 == 'A' or request.session.logueo.2 == 'E' or request.session.logueo.2 == 'C'  %}
<br>
<br><br>
<br>
<br><br>
<div class="container">
    <div class="row">
       <div class="col-md-12 ">
          <div class="titlepage">
             <h2>Comentarios</h2>
          </div>
       </div>
    </div>
    <h1>Comentarios</h1>
    <a href="{% url 'Freeforall:nuevoComentarios' %}" class="btn btn-primary">Crear</a>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Comentarios</th>
                    <th>Fecha ingreso</th>
                    <th>Evento</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for comentario in comentarios %}
                <tr>
                    <td>{{comentario.id_comentarios}}</td>
                    <td>{{comentario.comentarios}}</td>
                    <td>{{comentario.fecha_ingreso}}</td>
                    <td>{{comentario.id_evento}}</td>
                    <td>
                    <a href="{% url 'Freeforall:editarComentarios' comentario.id_comentarios %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'Freeforall:eliminarComentarios' comentario.id_comentarios %}" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>        
{% endif %}   
{% endblock %}

FFA/Freeforall/templates/Freeforall/comentarios/nuevo.html
{% extends 'Freeforall/base.html' %}
{% load static %}

{% block contenedor %}
{% if request.session.logueo.2 == 'A' or request.session.logueo.2 == 'E' or request.session.logueo.2 == 'C'  %}
<br>
<br><br>
<br>
<br><br>
<div class="container">
    <div class="row">
       <div class="col-md-12 ">
          <div class="titlepage">
             <h2>Registro Cometario</h2>
             <span> llena cada campo con los datos indicados</span>
          </div>
       </div>
    </div>
    <div class="container">
        <div class="row">
            <form class="col s12" action="{% url 'Freeforall:guardarComentarios' %}" method="POST">{% csrf_token %}
                <div class="row">
                    <label for="titulo">Comentario</label>
                    <div class="input-group">
                        <textarea class="form-control" aria-label="With textarea" type="text" name="comentarios" required></textarea>
                    </div>
            
                    <div class="input-field col s12">
                        <input value="{{ request.session.logueo.3 }}" id="titulo" type="hidden" class="form-control" name="usuarios" required>
                    </div>
                    <div class="input-field col s12">
                        <input value="{{ eventos.id_evento }}" id="titulo" type="hidden" class="form-control" name="eventos" required>
                    </div>
                        <button type="submit" class="btn btn-primary">Guardar liga</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>    
{% endif %}
{% endblock %}